name: Deploy sandbox

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test-2

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Verify branch
        run: |
          echo "Running from: ${GITHUB_REF}"

          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            echo "ERROR: This workflow can only be executed from the main branch."
            exit 1
          fi

  deploy:
    needs: validate

    runs-on: ubuntu-latest

    environment:
      name: Configure QA

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          echo "Deploying to QA from main branch..."
